### ISSUE TITLE
Using deltamass interface

### ISSUE THREAD

**Issue by iaime** [chhh/deltamass#6]
Hi, 

I am trying to analyze mass differences resulting form open search using MSFragger, and I was just doing a test using one file. But unfortunately, I am stuck with an error. I am attaching a screenshot of the GUI. I would appreciate any help.
![image](https://user-images.githubusercontent.com/37421209/57891468-78e7b280-7809-11e9-93a3-16ffec420eeb.png)

**Comment by chhh** [comment]
@iaime
Could you please share the file so i can investigate?
Are you using version 1.2.1? https://github.com/chhh/deltamass/releases/tag/1.2.1

**Comment by iaime** [comment]
Hi,
Yes, I am using version 1.2.1. I am attaching the file I am using. Thank you!

[20150708_QE3_UPLC8_DBJ_SA_Hela_39frac_Trypsin_39.pepXML.zip](https://github.com/chhh/deltamass/files/3196566/20150708_QE3_UPLC8_DBJ_SA_Hela_39frac_Trypsin_39.pepXML.zip)

**Comment by iaime** [comment]
Hi!
I was wondering if there is any update on the above issue. Thank you!

**Comment by chhh** [comment]
Sorry, not yet, traveling after ASMS, will work on it as soon as I get back.

**Comment by chhh** [comment]
Finally had the time to look at it. Your file does not seem to have modified peptide sequences for some reason. Added a fix/exception for such cases in new version 1.2.2.

With default settings you might think it misses a lot of peaks - if you want more peaks to be reported, lower the default setting `Min PSMs` from 10 to something smaller. However it's doubtful that a peak supported by less than 10 PSMs should be considered.

Download here: https://github.com/chhh/deltamass/releases/tag/1.2.2
